import { generate } from 'ts-to-zod'
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Collections to generate schemas for
const COLLECTIONS = [
  'User',
  'Media',
  'StaticPage',
  'BlogPost',
  'Country',
  'Company',
  'Category',
  'OrganisingGroup',
  'Campaign',
  'Action',
]

// Globals to generate schemas for
const GLOBALS = [
  'Header',
  'Footer',
  'StartOrganising',
  'AboutPage',
  'CampaignsPage',
  'DataPage',
  'ActionSubmissionPage',
]

function main() {
  const payloadTypesPath = path.resolve(__dirname, '../src/payload-types.ts')
  const outputPath = path.resolve(__dirname, '../src/payload-zod-schemas.ts')

  console.log(`Reading ${payloadTypesPath}...`)
  const sourceCode = fs.readFileSync(payloadTypesPath, 'utf-8')

  // Generate schemas for all collections and globals
  const typesToGenerate = [...COLLECTIONS, ...GLOBALS]

  console.log(`Generating Zod schemas`)
  //  for: ${typesToGenerate.join(', ')}...`)

  const result = generate({
    sourceText: sourceCode,
    nameFilter: (identifierName) => {
      // Only process the types we want
      return typesToGenerate.includes(identifierName)
    },
    getSchemaName: (identifierName: string) => {
      return `${identifierName}Schema`
    },
  })

  // Generate output - getZodSchemasFile returns the schemas with imports
  // We need to clean it up and fix the import path
  let schemasContent = result.getZodSchemasFile('./payload-types')

  // Remove duplicate zod imports and fix the types import
  schemasContent = schemasContent
    .replace(/import \{ z \} from "zod";/g, '') // Remove duplicate zod imports
    .replace(/import \{ type .* \} from "";/g, '') // Remove empty type imports
    .replace(/import \{ type .* \} from "\.\/payload-types";/g, '') // Remove type imports (we don't need them)
    .replace(/\/\/ Generated by ts-to-zod\n+/g, '') // Remove ts-to-zod comment
    .trim()

  const output = `/**
 * This file was automatically generated from payload-types.ts
 * DO NOT MODIFY IT BY HAND. Instead, modify the generator script and re-run it.
 * 
 * To regenerate: pnpm tsx scripts/generate-zod-schemas.ts
 */

import {
  User,
  Media,
  StaticPage,
  BlogPost,
  Country,
  Company,
  Category,
  OrganisingGroup,
  Campaign,
  Action,
} from '@/payload-types'
import { z } from 'zod'

${schemasContent}
`

  console.log(`Writing ${outputPath}...`)
  fs.writeFileSync(outputPath, output, 'utf-8')

  console.log(`\n✅ Generated Zod schemas for:`)
  // console.log(`  Collections: ${COLLECTIONS.join(', ')}`)
  // console.log(`  Globals: ${GLOBALS.join(', ')}`)
  console.log(`\n📝 Output written to: ${outputPath}`)
}

main()
